Feature: record structured output per shot, print json in transpile-to-quil
rigetti/qcs-sdk-qir pull request #27
Opened 2022-04-10 19:48 UTC by nilslice

Could use some help w/ best placement for `RecordedOutput` and ideal visibility... it needs to be `pub`, and while it is used internally to `qcs-sdk-qir`, it is also used in an external to-be-published crate.

2022-04-11 16:16 UTC, dbanty requested changes

2022-04-11 16:16 UTC, dbanty commented on src/transform/shot_count_block/pattern.rs
> +    static ref RT_RECORD_OUTPUT_INTRINSIC_REGEX: Regex =
Personally I'd prefer avoiding the regex and just matching against the literal strings. Would be a bit faster at runtime and, IMO, more readable (e.g., I can just search for the function name if I want to see where it's handled).

2022-04-11 16:16 UTC, dbanty commented on src/transform/shot_count_block/pattern.rs
> +                        "bool" | "integer" | "double" => todo!(),
Leave a comment and return an Err here please to avoid panics.

2022-04-11 16:16 UTC, dbanty commented on src/lib.rs
> +    ReadoutOffset(u64),
I think this should better indicate the type that was expected by the function call. We only support Result today but we might add more types in the future.

So specifically indicate somehow that this is the result function (so we know it should be 1 or 0)

2022-04-11 16:16 UTC, dbanty commented on Cargo.toml
> +serde = { version = "1", features = ["derive"] }
Serde stuff is only needed for CLI output right? Doesn't impact my usecase much but usually I see `serde` behind a feature flag so it doesn't have to get compiled in if the consumer doesn't need it.

2022-04-11 16:16 UTC, dbanty commented on tests/transpile-to-quil.md
> +  "recorded_output": [
Can you add tests which call the record functions to make sure that all looks good here?

2022-04-11 17:10 UTC, nilslice commented on src/lib.rs
> +    ReadoutOffset(u64),
I'll add the other types to support  and a new Error variant to indicate which aren't implemented yet 👍

2022-04-11 17:10 UTC, nilslice commented on Cargo.toml
> +serde = { version = "1", features = ["derive"] }
Yep can do

2022-04-11 17:57 UTC, nilslice commented on src/transform/shot_count_block/pattern.rs
> +    static ref RT_RECORD_OUTPUT_INTRINSIC_REGEX: Regex =
yea I tried this, and the match just looked overwhelming with the full function name, and it becomes more prone to error if someone misspells a fn name for example.

2022-04-11 18:46 UTC, nilslice commented on tests/transpile-to-quil.md
> +  "recorded_output": [
@dbanty - Sorry for the late follow-up, can you elaborate on this? There are tests that build up and verify some execution results and the mapping here for example: 
https://github.com/rigetti/qcs-sdk-qir/blob/e5f310e3258e0bbb8f7e89d94e823a865fe64228/src/output/debug.rs#L92-L148

2022-04-11 20:19 UTC, nilslice commented
Note: this PR bumps MSRV to the latest stable: 1.60.0 and updates the edition to 2021.

2022-04-13 00:26 UTC, kalzoo requested changes
lgtm, the trait seems like a good way to solve this - although I wonder if a simple function (like you have commented out) would serve the same purposes with less complexity. That is, implementers of that trait only exist to then be formatted into a string, so maybe just a function that formats directly to string would do the job?

2022-04-13 00:26 UTC, kalzoo commented on src/output/mod.rs
> +    /// impelemented, a `new` function can be added and this deprecated.
```suggestion
    /// implemented, a `new` function can be added and this deprecated.
```

2022-04-13 00:26 UTC, kalzoo commented on src/output/mod.rs
> +/// All errors that may be returned from `qcs-sdk-output-format` crate.
No longer its own crate

2022-04-13 00:26 UTC, kalzoo commented on src/output/debug.rs
> +impl From<DebugOutputFormat> for String {
Would this conventionally be `impl std::fmt::Display` which itself provides a `to_string` method?

2022-04-13 00:26 UTC, kalzoo commented on src/output/mod.rs
> +/// A generic function over `F`: [`OutputFormat`], which attempts to format program output based on
Still mean for this to be here?

2022-04-13 18:25 UTC, nilslice commented on src/output/mod.rs
> +/// A generic function over `F`: [`OutputFormat`], which attempts to format program output based on
"this" meaning the whole `try_format` function? if so, yea. the intent was to provide end users / integration partners with a simple generic function that they'd call and specify their own type (which impls `OutputFormat`) and a reference implementation `DebugOutputFormat`. 

The goal is two-fold: 
1. provide an environment-agnostic approach to printing output
2. offer guidelines / hints to use `ExecutionResult` and `RecordedOutput` to stitch the necessary information together for printing results.

2022-04-13 20:44 UTC, dbanty commented on tests/transpile-to-quil.md
> +  "recorded_output": [
I meant an e2e snapshot test similar to this one—where there's an input `.bc` file and we verify that the output Quil and record calls all look correct.

2022-04-13 21:10 UTC, nilslice commented on src/output/debug.rs
> +impl From<DebugOutputFormat> for String {
good call -- changed to use `Display` instead

2022-04-13 23:03 UTC, nilslice commented on tests/transpile-to-quil.md
> +  "recorded_output": [
Added!

2022-04-13 23:12 UTC, nilslice commented on src/output/mod.rs
> +/// A generic function over `F`: [`OutputFormat`], which attempts to format program output based on
ah, maybe you saw this large doc comment and thought the whole function was commented out? (referencing: https://github.com/rigetti/qcs-sdk-qir/pull/27#pullrequestreview-938039679)

> a simple function (like you have commented out)

At Line 87 there is a function `try_format`, which is quite small in comparison to the doc comment. maybe the one commented out you're referring to is the doc example/test?

2022-04-14 17:58 UTC, dbanty commented on Cargo.toml
> +serde_support = ["dep:serde", "dep:serde_json"]
Using the `dep:` syntax ups MSRV to 1.60. I think that's fine for my usage, but I would have gotten a nicer error at build time if `rust-version` was set in here. Can you add that if upping MSRV to 1.60 is intentional or, otherwise, change this syntax?

2022-04-14 17:58 UTC, dbanty commented on Cargo.toml
> +serde_support = ["dep:serde", "dep:serde_json"]
Using the `dep:` syntax ups MSRV to 1.60. I think that's fine for my usage, but I would have gotten a nicer error at build time if `rust-version` was set in here. Can you add that if upping MSRV to 1.60 is intentional or, otherwise, change this syntax?

2022-04-14 18:27 UTC, nilslice commented on Cargo.toml
> +serde_support = ["dep:serde", "dep:serde_json"]
@dbanty - yea, in fact I just couldn't get this to work _without_ using the `dep:` syntax... would be happy to know how it could work the same and not bump MSRV to 1.60? 

The change was intentional, and that's what there's a `rust-toolchain.toml` in the crate now. But, it was only to get this to work at all.

2022-04-14 19:49 UTC, dbanty commented on Cargo.toml
> +serde_support = ["dep:serde", "dep:serde_json"]
You should just be able to do `["serde", "serde_json"]`. The `dep:` syntax is only to differentiate from other feature names (and to prevent adding extra features named `serde` and `serde_json` as is the default) I think.

2022-04-14 20:00 UTC, nilslice commented on Cargo.toml
> +serde_support = ["dep:serde", "dep:serde_json"]
I'll try it again, but doing so didn't enable those when I had originally used that approach 🤷

2022-04-14 20:14 UTC, nilslice commented on Cargo.toml
> +serde_support = ["dep:serde", "dep:serde_json"]
ok, well... it worked this time 😆 thx Dylan!

2022-04-14 20:28 UTC, nilslice commented on src/output/mod.rs
> +/// A generic function over `F`: [`OutputFormat`], which attempts to format program output based on
> maybe just a function that formats directly to string would do the job?

`try_format` exists to do just that. and the trait is meant to be flexible, such that you can always decorate your impl type (eg `DebugOutputFormat`) with other fields / methods so in the `Display` impl you can grab whatever other data you want to be injected into the output string (either in aggregate or per-row). 

```rust
struct MyPlatformOutputFormat {
   output: Vec<String>,
   customer_id: u64,
   task_id: u64,
}

impl OutputFormat for MyPlatformOutputFormat { ... } // where `self.output` is the raw recorded output 

// inject the platform-specific values to the raw recorded output
impl Display for MyPlatformOutputFormat {
   fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(
            &self.output.iter().map(|output_row| { 
                format!(
                    "{} | {} | {}", 
                    self.customer_id, self.task_id, output_row
                )
            }
        ).collect().join("\n"))
   }
}
```

(not claiming that compiles, but you get the gist!)

2022-04-14 20:59 UTC, dbanty approved these changes
LGTM 🎸 . I left a couple comments & questions but certainly nothing blocking.

2022-04-14 20:59 UTC, dbanty commented on src/output/debug.rs
> +    ///
```suggestion
    ///
    /// # Arguments
    ///
    /// - `result`: The output returned from the [`qcs`] crate.
    /// - `mapping`: The [`crate::ProgramOutput::recorded_output`] field from a call to [`crate::transpile_qir_to_quil`]
```

Maybe not useful in the context of this crate, but that was the sort of thing I was trying to do in my own docstrings (thus needing the re-export of `ProgramOutput`. I have not actually tested this docstring so my links could be off.

2022-04-14 20:59 UTC, dbanty commented on src/output/debug.rs
> +                                // TODO: determine if we need the upstream `index` to be 64-bit.
Did you TODO this?

2022-04-14 20:59 UTC, dbanty commented on src/output/debug.rs
> +#[test]
Does `#[test]` also skip compilation if not compiling for tests? I always stick my unit tests in a mod covered by `#[cfg(test)]` because that's how I've seen it done and I didn't question it 😅

2022-04-14 20:59 UTC, dbanty commented on src/output/mod.rs
> +#![deny(clippy::pedantic)]
Doesn't this statement being in `lib.rs` imply it everywhere else in the crate?

2022-04-14 20:59 UTC, dbanty commented on src/transform/shot_count_block/pattern.rs
> +    static ref RT_RECORD_OUTPUT_INTRINSIC_REGEX: Regex =
I more meant putting the function names in constants and matching on those—but no big difference either way.

2022-04-14 20:59 UTC, dbanty commented on src/transform/shot_count_block/pattern.rs
> +                            return Err(eyre!("unimplemented record type: {}", record_type));
Should this use `output::Error::UnimplementedRecordType`? It'll probably get erased by `eyre` further up right now—but eventually, we won't want to be exporting `eyre::Report` because it goes strictly against the recommendations of the author (we just did it for now for ease of writing). So using the new error type you created will mean slightly less work in the future 🤷

2022-04-14 21:05 UTC, nilslice commented on src/output/debug.rs
> +                                // TODO: determine if we need the upstream `index` to be 64-bit.
yes - this is the thing we were discussing that could use some input from @kalzoo... elsewhere, the `pattern_context.read_result_mapping` has `u64`'s and it causes lots of other places to need to cast (while potentially truncating) to `usize` when using as indices. 

I think I've also seen some conversation in `quil-rust` (maybe?) about wanting an architecture-independent type for these kinds of values, which makes sense, but it does make things a little worse in situations like the one here.

2022-04-14 21:06 UTC, nilslice commented on src/output/debug.rs
> +#[test]
yep! i think they have largely the same effect. #[test] may only work on `fn`s and the other is like a block-scoped attr ?

2022-04-14 21:06 UTC, nilslice commented on src/output/mod.rs
> +#![deny(clippy::pedantic)]
probably just copied/pasted with the copyright header.. will remove!

2022-04-14 21:15 UTC, nilslice commented on src/transform/shot_count_block/pattern.rs
> +                            return Err(eyre!("unimplemented record type: {}", record_type));
I think we'll probably want a different set of errors for this section of the code. `output::Error::UnimplementedRecordType` is meant for the implementer (the consumer of the mapping) and indicates that the source program contained instructions that the particular implementer doesn't expect to handle. 

The code referenced here (the error at L518) is where the sdk scans the IR to build-up the mapping itself.. the fact that we have this match arm returning the `Err` doesn't necessarily mean that the downstream implementer must expect the same. The point being, while we could use the new `output::Error` type, I think we'd end up changing it again anyways to use some Error type created more specifically for this part of the program.

2022-04-14 21:21 UTC, nilslice commented on src/output/debug.rs
> +    ///
just tested w/ cargo doc and it links up nicely -- added!

2022-04-15 16:18 UTC, kalzoo commented on src/output/debug.rs
> +                                // TODO: determine if we need the upstream `index` to be 64-bit.
Yeah, we also have to consider the input data type from LLVM: 

https://github.com/rigetti/qcs-sdk-qir/blob/main/src/interop/instruction.rs#L89
https://github.com/rigetti/qcs-sdk-qir/blob/main/src/interop/instruction.rs#L138

We could perform a conversion to whatever type we'd like there. As from that `quil-rust` conversation though, I don't know if constraining result index to `usize` makes sense just to support the fact that internally we store shots in a `Vec`. Here, this should probably be a `usize::try_from` so that any misbehavior is obvious.

As far as the TODO, let's capture it as an issue if we'd like to resolve it later, and either tag the comment with the issue # or remove it - it's not the only TODO in the crate of course but as this goes into production, it's good to capture them in a more actionable way.

2022-04-15 16:18 UTC, kalzoo commented on src/output/mod.rs
> +/// A generic function over `F`: [`OutputFormat`], which attempts to format program output based on
Thanks for that! Looks good to me.

2022-04-15 16:18 UTC, kalzoo commented on src/transform/shot_count_block/pattern.rs
> +                            debug!("visited: {:?}", function_name);
I think this one in particular is left over from the development work

2022-04-15 16:40 UTC, nilslice commented on src/output/debug.rs
> +                                // TODO: determine if we need the upstream `index` to be 64-bit.
tracking issue here: https://github.com/rigetti/qcs-sdk-qir/issues/29

2022-04-15 16:43 UTC, kalzoo approved these changes

2022-04-15 16:56 UTC, merged